# Generated by Django 4.2.7 on 2023-11-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tienda_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tienda",
            name="abv",
        ),
        migrations.RemoveField(
            model_name="tienda",
            name="rating",
        ),
        migrations.AlterField(
            model_name="tienda",
            name="nombre",
            field=models.CharField(default="tienda x", max_length=100),
        ),
    ]
